language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
 script: ./gradlew clean check || cat /home/travis/build/graphql-java/graphql-spring-boot/graphql-spring-boot-autoconfigure/build/reports/tests/test/index.html
