spring:
  application:
    name: graphql-java-tools-app
server:
  port: 9000
graphiql:
  props:
    resources:
      query: defaultQuery.graphql
      defaultQuery: defaultQuery.graphql
      variables: defaultQuery.graphql
